name: Backdrop Code Review

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-standards:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.3']

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set up PHP ${{ matrix.php_version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}

    - name: Install dependencies
      run: composer install --dev

    - name: Composer version
      run: composer -V

    - name: Install Codesniffer
      run: composer global require dealerdirect/phpcodesniffer-composer-installer

    - name: Install Coder
      run: git clone git@github.com:backdrop-contrib/coder_review.git coder_review

    - name: Verify Registered Standards
      run: ~/.composer/vendor/bin/phpcs -i

    - name: Manually Set Installed Paths
      run: ~/.composer/vendor/bin/phpcs --config-set installed_paths coder_review/coder_sniffer

    - name: Code review initiated
      run: |
        ~/.composer/vendor/bin/phpcs --standard=Backdrop --extensions=php,module,inc,install,test,css,info,txt,md ./
