on: pull_request

name: Backdrop Code Review

jobs:
  runPHPCSInspection:
    name: Run PHPCS Backdrop Code Review
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['5.6']

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up PHP ${{ matrix.php_version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}

    - name: Download Coder review
      run: wget https://github.com/backdrop-contrib/coder_review/releases/download/1.x-1.0.1-beta/coder_review.zip ~/.

    - name: Unzip Coder review
      run: unzip ~/coder_review.zip

    - name: change to Coder review dir
      run: cd ~/coder_review

    - name: Get coder_review patch
      run: wget https://github.com/backdrop-contrib/coder_review/pull/14.patch

    - name: Apply coder_review patch
      run: patch -p1 < 14.patch

    - name: Install Codesniffer
      run: composer global require squizlabs/php_codesniffer:3.5.6

    - name: List all of the available packages
      run: composer global show -P

    - name: Composer home directory
      run: composer global config home

    - name: Verify Registered Standards
      run: ~/.composer/vendor/bin/phpcs -i

    - name: Manually Set Installed Paths
      run: ~/.composer/vendor/bin/phpcs --config-set installed_paths ~/coder_review/coder_sniffer

    - name: Code review initiated
      run: ~/.composer/vendor/bin/phpcs --standard=Backdrop --extensions=php,module,inc,install,test,css,info,txt,md ./
